package: slice_cap

version: '1.1.0'
author: 'LuS'
supportpage: https://github.com/Laut-und-Schoen/slice_cap

requires:
    php:
        version: '>=8.1'
    redaxo: ^5.18
    packages:
        structure/content: '^2.11'
