package: slice_cap

version: '1.1.3'
author: 'Norbert Micheel'
supportpage: https://github.com/tyrant88/slice_cap

requires:
    php:
        version: '>=8.1'
    redaxo: ^5.18
    packages:
        structure/content: '^2.11'
